name: TTT
authors:
  - z1up
version: b1.0
main: de.z1up.ttt.TTT

commands:
  addmap:
  build:
  start:
  setspawn:
  forcemap:
  removespawn:
  map:
  stats:
  setspecspawn:
  setlobbyspawn:
  setholo:
